# Use an official Node.js runtime as the base image
FROM node:20-alpine AS development

# Set the working directory
WORKDIR /opt/app

# Copy package.json and yarn.lock to install dependencies
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Expose the port Strapi runs on
EXPOSE 1337

# Command to run Strapi in development mode
CMD ["yarn", "develop"]