export default () => ({
    meilisearch: {
    config: {
      // Your meili host
      host: 'https://search.admin.duhochappytime.edu.vn',
      // Your master key or private key
      apiKey: 'MTj1RK5WnhlQqkP0Z4PrtIKnQF8Xo_xwx2pH8-rDE3U',
    },
    // ckeditor: {
    //   enabled: true,
    //   config: {
    //     editor : {
    //       plugins: [
    //         'Alignment',
    //         'Autoformat',
    //         'BlockQuote',
    //         'Bold',
    //         'Code',
    //         'CodeBlock',
    //         'Essentials',
    //         'FontBackgroundColor',
    //         'FontColor',
    //         'FontFamily',
    //         'FontSize',
    //         'Heading',
    //         'Highlight',
    //         'HorizontalLine',
    //         'Image',
    //         'Indent',
    //         'Italic',
    //         'Link',
    //         'ListStyle',
    //         'MediaEmbed',
    //         'Paragraph',
    //         'PasteFromOffice',
    //         'Table',
    //         'SourceEditing',
    //       ],
    //       toolbar: [
    //         'heading',
    //         '|',
    //         'bold',
    //         'italic',
    //         'link',
    //         '|',
    //         'bulletedList',
    //         'numberedList',
    //         'blockQuote',
    //         '|',
    //         'insertTable',
    //         'mediaEmbed',
    //         '|',
    //         'undo',
    //         'redo',
    //         '|',
    //         'alignment',
    //         'fontBackgroundColor',
    //         'fontColor',
    //         'fontFamily',
    //         'fontSize',
    //         'highlight',
    //         'horizontalLine',
    //         'sourceEditing',
    //       ],
    //     },
    //   },
    // },
  },
});
